name: Build & Deploy Jupyter Book (Incomplete)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "No operation. See DesignSafe-CI/training-Computational-Workflows-on-DesignSafe#1"
